name: magic_workout_app
description: "Workout App techincal task for Magic AI"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  go_router: ^14.2.7
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.4.0
  uuid: ^4.5.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/